[prune]
  go-tests = true

[[constraint]]
  name = "github.com/TIBCOSoftware/flogo-contrib"
  branch = "master"

[[constraint]]
  name = "github.com/TIBCOSoftware/flogo-lib"
  branch = "master"

[[constraint]]
  name = "github.com/apache/thrift"
  branch = "master"
